// Package azlyrics provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package azlyrics

// Error defines model for Error.
type Error struct {

	// Machine-readable error code.
	Code string `json:"code"`

	// A brief description of what kind of error was received
	Message string `json:"message"`
}

// FetchRequest defines model for FetchRequest.
type FetchRequest struct {

	// The name of the artist
	Artist string `json:"artist"`

	// The title of the song
	Title string `json:"title"`
}

// FetchResponse defines model for FetchResponse.
type FetchResponse struct {
	Errors *Error `json:"errors,omitempty"`

	// The lyrics of the song
	Lyrics string `json:"lyrics"`
}

// PostFetchJSONBody defines parameters for PostFetch.
type PostFetchJSONBody FetchRequest

// PostFetchRequestBody defines body for PostFetch for application/json ContentType.
type PostFetchJSONRequestBody PostFetchJSONBody

