// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// LyricClient is an autogenerated mock type for the LyricClient type
type LyricClient struct {
	mock.Mock
}

// GetLyrics provides a mock function with given fields: ctx, artistName, songTitle
func (_m *LyricClient) GetLyrics(ctx context.Context, artistName string, songTitle string) (string, error) {
	ret := _m.Called(ctx, artistName, songTitle)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, artistName, songTitle)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, artistName, songTitle)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
